---
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Towards best practices in bioclimatic envelope modelling: testing the importance of predictor choice, modelling technique selection, and number of pseudo-absences

Authors: Mirza Čengić^1‡^, Jasmijn Rost^2‡^, Mark A.J. Huijbregts^1^, Daniela Remenska^3^, Jan H. Janse^2^, Aafke M. Schipper^1,2^

^1^ Department of Environmental Science, Institute for Water and Wetland Research, Radboud University Nijmegen, P.O. Box 9010, 6500 GL Nijmegen, The Netherlands  
^2^ PBL Netherlands Environmental Assessment Agency, P.O. Box 30314, 2500 GH The Hague, The Netherlands  
^3^ Netherlands eScience Center, Science Park 140, 1098 XG Amsterdam, The Netherlands  
^‡^ Both authors contributed equally to this manuscript  


---

#### Abstract  

Bioclimatic envelope models are commonly used to quantify the influence of future climate change on species’ distributions and biodiversity patterns. Improving our understanding of the accuracy and robustness of these models is critical for outlining best practices. Here we systematically evaluate the performance of bioclimatic envelope models in relation to the selection of predictors, modelling technique and pseudo-absences. We considered (i) four predictor sets consisting out of 2, 4, 10 or 19 bioclimatic variables, (ii) seven commonly used modelling techniques and an ensemble model, and (iii) three sets of pseudo-absences (1 000, 10 000 and the same as the number of presences). For each combination of predictor set, modelling technique and pseudo-absence set, we fitted bioclimatic envelope models for 300 species of mammals, amphibians and freshwater fish, and evaluated the predictive performance of the models using the True Skill Statistic (TSS), based on a spatially independent test set as well as cross-validation. On average across the species, model performance was mostly influenced by the choice of predictor set, followed by the choice of modelling technique. The number of the pseudo-absences did not have a strong effect on the model performance. Based on spatially independent testing, an ensemble model with 10 or 19 predictors revealed the highest predictive performance. In contrast, the random forest technique yielded the highest model performance in the cross-validation, thus highlighting the need for spatially independent model evaluation. We recommend building bioclimatic envelope models according to an ensemble modelling approach based on a non-redundant set of bioclimatic predictors.
